import type { DashboardSourceDomainName } from './dashboard-source-base.types';

export const DASHBOARD_SOURCE_FIELD_MAP: Record<
  DashboardSourceDomainName,
  readonly string[]
> = {
  agreement: [
    'id',
    'freelancerId',
    'clientId',
    'title',
    'totalAmount',
    'currency',
    'status',
    'createdAt',
    'updatedAt',
  ],
  client: ['id', 'freelancerId', 'name', 'email', 'createdAt'],
  milestone: [
    'id',
    'agreementId',
    'title',
    'amount',
    'currency',
    'status',
    'paymentStatus',
    'deliveryStatus',
    'dueDate',
    'order',
    'createdAt',
    'updatedAt',
  ],
  payment: [
    'id',
    'agreementId',
    'milestoneId',
    'changeRequestId',
    'amount',
    'currency',
    'status',
    'operationType',
    'demoMode',
    'reservedAt',
    'releasedAt',
    'createdAt',
    'updatedAt',
  ],
  delivery: [
    'id',
    'agreementId',
    'milestoneId',
    'status',
    'submittedAt',
    'createdAt',
    'updatedAt',
  ],
  aiReview: [
    'id',
    'agreementId',
    'milestoneId',
    'deliveryId',
    'status',
    'recommendation',
    'matchScore',
    'createdAt',
    'updatedAt',
  ],
  changeRequest: [
    'id',
    'agreementId',
    'milestoneId',
    'title',
    'amount',
    'currency',
    'status',
    'paymentStatus',
    'createdAt',
    'updatedAt',
  ],
  timelineEvent: [
    'id',
    'agreementId',
    'milestoneId',
    'type',
    'title',
    'description',
    'actorRole',
    'actorId',
    'metadata',
    'createdAt',
  ],
} as const;
