-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'AI_REVIEW_RECOMMENDATION_ACCEPTED';

-- AlterEnum
ALTER TYPE "TimelineEventType" ADD VALUE 'AI_REVIEW_RECOMMENDATION_ACCEPTED';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'FREELANCER';
