import { PaymentOperationType, PaymentStatus } from '@prisma/client';
import { SeedClient, SeedContext } from './types';

const payments = [
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1',
    agreementKey: 'activePortal',
    milestoneKey: 'portalDiscovery',
    changeRequestKey: null,
    amount: '9000.00',
    currency: 'SAR',
    status: PaymentStatus.RELEASED,
    operationType: PaymentOperationType.RELEASE_MILESTONE,
    receiptNumber: 'RCPT-SEED-0001',
    transactionReference: 'TX-SEED-0001',
    reservedAt: new Date('2026-05-08T12:00:00.000Z'),
    releasedAt: new Date('2026-05-24T09:00:00.000Z'),
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2',
    agreementKey: 'activePortal',
    milestoneKey: 'portalBuild',
    changeRequestKey: null,
    amount: '23000.00',
    currency: 'SAR',
    status: PaymentStatus.CLIENT_REVIEW,
    operationType: PaymentOperationType.FUND_MILESTONE,
    receiptNumber: 'RCPT-SEED-0002',
    transactionReference: 'TX-SEED-0002',
    reservedAt: new Date('2026-05-25T10:00:00.000Z'),
    releasedAt: null,
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3',
    agreementKey: 'activePortal',
    milestoneKey: 'portalLaunch',
    changeRequestKey: null,
    amount: '10000.00',
    currency: 'SAR',
    status: PaymentStatus.RESERVED,
    operationType: PaymentOperationType.FUND_MILESTONE,
    receiptNumber: 'RCPT-SEED-0003',
    transactionReference: 'TX-SEED-0003',
    reservedAt: new Date('2026-06-01T10:00:00.000Z'),
    releasedAt: null,
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4',
    agreementKey: 'disputedClinic',
    milestoneKey: 'clinicFrontend',
    changeRequestKey: null,
    amount: '17000.00',
    currency: 'SAR',
    status: PaymentStatus.AI_REVIEW,
    operationType: PaymentOperationType.FUND_MILESTONE,
    receiptNumber: 'RCPT-SEED-0004',
    transactionReference: 'TX-SEED-0004',
    reservedAt: new Date('2026-04-18T15:00:00.000Z'),
    releasedAt: null,
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5',
    agreementKey: 'disputedClinic',
    milestoneKey: 'clinicFrontend',
    changeRequestKey: 'clinicArabicFix',
    amount: '1800.00',
    currency: 'SAR',
    status: PaymentStatus.RESERVED,
    operationType: PaymentOperationType.CHANGE_REQUEST_PAYMENT,
    receiptNumber: 'RCPT-SEED-0005',
    transactionReference: 'TX-SEED-0005',
    reservedAt: new Date('2026-05-20T10:30:00.000Z'),
    releasedAt: null,
  },
  {
    id: 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6',
    agreementKey: 'completedBrand',
    milestoneKey: 'brandKit',
    changeRequestKey: null,
    amount: '9500.00',
    currency: 'USD',
    status: PaymentStatus.RELEASED,
    operationType: PaymentOperationType.RELEASE_MILESTONE,
    receiptNumber: 'RCPT-SEED-0006',
    transactionReference: 'TX-SEED-0006',
    reservedAt: new Date('2026-03-14T13:00:00.000Z'),
    releasedAt: new Date('2026-04-08T10:00:00.000Z'),
  },
] as const;

export async function seedPayments(
  prisma: SeedClient,
  context: SeedContext,
): Promise<void> {
  for (const payment of payments) {
    await prisma.payment.upsert({
      where: { id: payment.id },
      update: {
        agreementId: context.agreements[payment.agreementKey],
        amount: payment.amount,
        changeRequestId: payment.changeRequestKey
          ? context.changeRequests[payment.changeRequestKey]
          : null,
        currency: payment.currency,
        demoMode: true,
        milestoneId: context.milestones[payment.milestoneKey],
        operationType: payment.operationType,
        paymentMethodLabel: 'Demo escrow balance',
        receiptNumber: payment.receiptNumber,
        releasedAt: payment.releasedAt,
        reservedAt: payment.reservedAt,
        status: payment.status,
        transactionReference: payment.transactionReference,
      },
      create: {
        id: payment.id,
        agreementId: context.agreements[payment.agreementKey],
        amount: payment.amount,
        changeRequestId: payment.changeRequestKey
          ? context.changeRequests[payment.changeRequestKey]
          : null,
        currency: payment.currency,
        demoMode: true,
        milestoneId: context.milestones[payment.milestoneKey],
        operationType: payment.operationType,
        paymentMethodLabel: 'Demo escrow balance',
        receiptNumber: payment.receiptNumber,
        releasedAt: payment.releasedAt,
        reservedAt: payment.reservedAt,
        status: payment.status,
        transactionReference: payment.transactionReference,
      },
    });
  }
}
