export enum DeliveryStatus {
  DRAFT = 'DRAFT',
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  SUBMITTED = 'SUBMITTED',
  CLIENT_REVIEW = 'CLIENT_REVIEW',
  IN_REVIEW = 'IN_REVIEW',
  ACCEPTED = 'ACCEPTED',
  CHANGES_REQUESTED = 'CHANGES_REQUESTED',
  DISPUTED = 'DISPUTED',
}
