export enum NotificationType {
  AGREEMENT_INVITE = 'AGREEMENT_INVITE',
  AGREEMENT_APPROVED = 'AGREEMENT_APPROVED',
  PAYMENT_RESERVED = 'PAYMENT_RESERVED',
  PAYMENT_RELEASED = 'PAYMENT_RELEASED',
  DELIVERY_SUBMITTED = 'DELIVERY_SUBMITTED',
  DELIVERY_CHANGES_REQUESTED = 'DELIVERY_CHANGES_REQUESTED',
  CHANGE_REQUEST_CREATED = 'CHANGE_REQUEST_CREATED',
  AI_REVIEW_READY = 'AI_REVIEW_READY',
  AGREEMENT_ACTIVATED = 'AGREEMENT_ACTIVATED',
  AGREEMENT_CANCELLED = 'AGREEMENT_CANCELLED',
}
